### ISSUE TITLE
Is this still applicable for the rPi?

### ISSUE THREAD

**Issue by cbarratt** [riptidewave93/RFLED-Server#11]
Hey

So I came across your blog post about soldering on the module to the rPi to make it work over Ethernet. 

Is this still a working solution with the current codebase? (it seems it's now ported to Go).

Assuming that you can still use the easybulb app to sync the bulbs and would still be homebridge compatible? Apologies for what may seem an easy answer, hardware/electronics is beyond me. Currently i use the milight bridge with ios 10 home app and apple tv as the bridge.

Thanks

**Comment by riptidewave93** [comment]
Hey there,

Yep, the new Go base still works on the Pi, and I personally run it on an original Pi Model B without issue on Raspbian 8.

As for your question, this works with all Miilight supported applications as far as I know. I personally use RGBLEDController on my android without issue.
