### ISSUE TITLE
[Not an issue, just a hint] Python implementation supporting multiple bridges

### ISSUE THREAD

**Issue by pfink** [riptidewave93/RFLED-Server#12]
Hi,
some months ago I forked and heavily extended this app to support multiple bridges on a single Raspberry Pi. Now, as my project strongly drifted apart from this one, I detached my fork - it's now available here: https://github.com/pfink/rfled-server-python (I use it on my own with 2 bridges for several months now without any problems)

I just thought I leave a note here, maybe you want to add a link on the README, if there are people looking for a python implementation or for multi-bridge support.

Finally, thank you for sharing your work which helped me very much improving my light installation at home ;-)

**Comment by riptidewave93** [comment]
Hey,

Thanks for the information. Added in https://github.com/riptidewave93/RFLED-Server/commit/68cbf57202e26fad18e64103b9b7e35cd05af23d
