### ISSUE TITLE
RFLED-Server for Jessie

### ISSUE THREAD

**Issue by sisamiwe** [riptidewave93/RFLED-Server#13]
Hi,

 I'm Michael from Germany and I want to use your RF LED server an a RPi3
with Jessie.

I was following the given installation instruction on github and I also
changed the interfaces as described here.

When I try to start the server, it does not work.

> (#)~:$

 systemctl start rfled-server.service
Job for rfled-server.service failed. See 'systemctl status
rfled-server.service' and 'journalctl -xn' for details.
[Exit 1 ]
(#)~:$ systemctl status rfled-server.service
● rfled-server.service - LSB: RFLED-Server for Milight LEDs
   Loaded: loaded (/etc/init.d/rfled-server)
   Active: failed (Result: exit-code) since Sat 2017-02-04 18:08:18 CET; 5s
ago
  Process: 5192 ExecStart=/etc/init.d/rfled-server start (code=exited,
status=127)

Feb 04 18:08:18 smarthomeng rfled-server[5192]: /etc/init.d/rfled-server: 6:
/etc/default/rfled-server: -serial: not found
Feb 04 18:08:18 smarthomeng systemd[1]: rfled-server.service: control
process exited, code=exited status=127
Feb 04 18:08:18 smarthomeng systemd[1]: Failed to start LSB: RFLED-Server
for Milight LEDs.
Feb 04 18:08:18 smarthomeng systemd[1]: Unit rfled-server.service entered
failed state.
[Exit 3 ]
(#)~:$

May you help?
It would be very nice.

THX

**Comment by riptidewave93** [comment]
Hey Michael,

Thanks for making an issue. From the output, it sounds like your /etc/default/rfled-server may not be configured correctly. Can you please share the contents of this file?

There have also been some reports of issues with the rPi3 due to the way the UART pins are used on the board. You may need to disable the on board Bluetooth and swap UART pins to get it working correctly. More info on this is at http://raspberrypi.stackexchange.com/a/45571

**Comment by sisamiwe** [comment]
Hey Chris,
thanks for your response.

I have already swapped the UART pins to have the serial0 on or as /dev/ttyAMA0

Output is
```
sudo service rfled-server start
Job for rfled-server.service failed. See 'systemctl status rfled-server.service' and 'journalctl -xn' for details
```.

the systemctl status rfled-server.service tells:
```
`(#)~:$ systemctl status rfled-server.service                                                                     21:13:02
● rfled-server.service - LSB: RFLED-Server for Milight LEDs
   Loaded: loaded (/etc/init.d/rfled-server)
   Active: failed (Result: exit-code) since Sat 2017-02-04 21:10:21 CET; 2min 43s ago
  Process: 10367 ExecStart=/etc/init.d/rfled-server start (code=exited, status=127)

Feb 04 21:10:21 smarthomeng rfled-server[10367]: /etc/init.d/rfled-server: 6: /etc/default/rfled-server: -serial:...found
Feb 04 21:10:21 smarthomeng systemd[1]: rfled-server.service: control process exited, code=exited status=127
Feb 04 21:10:21 smarthomeng systemd[1]: Failed to start LSB: RFLED-Server for Milight LEDs.
Feb 04 21:10:21 smarthomeng systemd[1]: Unit rfled-server.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.`
```

Via putty (telnet) I can start the server with
`rfled-server -serial /dev/ttyAMA0`

Doing that I can control the milights via the modified bridge and RFserver. If I escape rfled-server, the control is stopped.

And finally here is my /etc/default/rfled-server:
`# Default settings for rfled-server. This file is sourced by /bin/sh from
# /etc/init.d/rfled-server.

# Define any options you want to be used when running. You can run rfled-server -h
# to get the list of available flags for this service.
RFLED_OPTS=” -serial /dev/ttyAMA0”`

**Comment by riptidewave93** [comment]
@sisamiwe Seems this issue was closed, were you able to resolve the issue?

If not, can you try manually running the binary to see if it launches? `rfled-server -serial /dev/ttyAMA0` Also note if your interface is /dev/ttyAMA0, you can remove this from RFLED_OPTS as this is set as default at https://github.com/riptidewave93/RFLED-Server/blob/master/src/rfled-server.go#L88

**Comment by sisamiwe** [comment]
No, the issue isn't closed. It is still there.

If I run the binary manually the `rfled-server -serial /dev/ttyAMA0` it is working.
`(#)~:$ rfled-server -serial /dev/ttyAMA0                                20:59:21
2017/02/15 20:59:23 "rfled-server started!"
`
As long the server is running, putty input is blocked. Using strg+c the server is terminated  and putty is working again.

Basically the issue is to get the server starting at boot using systemctl as it is usual for Jessie.
What do you suggest?

**Comment by riptidewave93** [comment]
@sisamiwe As mentioned earlier, try removing `” -serial /dev/ttyAMA0”` from your /etc/default/rfled-server as this is default already within the binary. You will also want to make sure that /dev/ttyAMA0 is not configured as a UART out for the console. More info on this is at https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=148109

**Comment by sisamiwe** [comment]
Chris,
I've removed `-serial /dev/ttyAMA0` from your /etc/default/rfled-server and I also made sure, that my  /dev/ttyAMA0 is not configured as a UART.

Now it works. Removing `-serial /dev/ttyAMA0` was the key!

Thank you!
