### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by xvolte** [riptidewave93/RFLED-Server#9]
Hello,

I'm trying to use your server for milight.

Unfortunately, i don't have the same device as yours, i ordered a 2.4 ghz emitter/receiver, that is connected to my SPI on the raspberry.

The device is working fine, as i can get it to send proper commands to the lights.

I would be interested of using the same server as yours, but instead of using the device directly, call my program "openmilight" directly into your code.

could you please give details on what the IOS or Android AP are sending to the server ?
My program works like this : 

/home/pi/xmili "B0 F2 EA 04 91 03 40"

So it is sending directly what the remote should be sending.

i figure in the source code this needs to be replaced :
_, err = s.Write(buf[:msg])
to something like exec "/home/pi/xmili", buf[:msg] (but i don't know the syntax, i'm not familiar with golang

Thank you very much in advance,

**Comment by riptidewave93** [comment]
So to start, my app expects standard miilight packets to be sent to it in the format described in the documentation over at http://www.limitlessled.com/dev/ under the "RGB+W LimitlessLED Light Bulb Commands" section.

As for sending commands to your app, this can be done in GoLang using _exec.Command_, similar to https://github.com/riptidewave93/RFLED-Server/blob/master/src/rfled-server.go#L104

You could strip out the UART calls (ex https://github.com/riptidewave93/RFLED-Server/blob/master/src/rfled-server.go#L53) and replace it with these _exec.Command_ calls, but it may be a bit inefficient.
